### ISSUE TITLE
gh-pages branch

### ISSUE THREAD

**Issue by BigBlueHat** [RWCBook/transitions-spec#1]
It'd be super to view this online. I forked it and made a gh-pages branch and :tada: a browse-able spec thingie!

If you want to add me as a contributor, I can do the grunt work...as I know you're busy. :wink:

**Comment by BigBlueHat** [comment]
http://bigbluehat.github.io/transitions-spec/

**Comment by mamund** [comment]
Yes. I'll added you later today. Also plan to futon the HAL-FORMS asked and
an updated Cj spec here. They would benefit firm the same treatment, too.
Maybe a short spec for the Siren object profile, too.

Thanks for being pro-active on this!

**Comment by BigBlueHat** [comment]
Haha. I any message was ever posted from a phone, that one was. :wink:

I think I got the gist of it, though! :smile_cat:

**Comment by mamund** [comment]
Bwahahahaha.

**Comment by BigBlueHat** [comment]
Here's what happens when you branch `master` and push `gh-pages` branch:
http://bigbluehat.github.io/transitions-spec

:smile_cat:

**Comment by mamund** [comment]
ha! works for me​

**Comment by BigBlueHat** [comment]
Tried to push it here, but I lack privs. :confused: 

I plan to do this with all the others too, btw. Just handy for people seeing stuff. :smile:

**Comment by mamund** [comment]
ok, i want to change the name of this repo (actually create a new one) to
wstl-spec.

then i'll add your rights.

and, yes, if by other ones you mean the POD spec and HAL-FORMS.

i also need to write up the SUGGEST Cj extension and create a new update
for the Cj spec which i can clone to here.

cheers.

mamund
Mike Amundsen
+1.859.757.1449
skype: mca.amundsen
http://amundsen.com/blog/
http://twitter.com/mamund
https://github.com/mamund
http://linkedin.com/in/mamund

**Comment by BigBlueHat** [comment]
Added! http://rwcbook.github.io/wstl-spec/

You might want to add the URL to the heading area on GitHub so folks can find it. I'll update the README.

Also, you can optionally make the `gh-pages` branch be the only/default branch--if you're OK with a "straight to web" sort of publishing pipeline. :grin: That's completely optional though.

**Comment by BigBlueHat** [comment]
Oh. I just found this--which I'm going to use on this and `pod-spec` for pushing to both master and gh-pages for the time being:
http://aarun.me/2015/06/24/github-automate-sync-between-master-and-gh-pages/

Handy! :hand:

**Comment by mamund** [comment]
@BigBlueHat 

I finally added the "sync between master and gh-pages" trick to my local config, too.

nice.
