### ISSUE TITLE
README name is wrong

### ISSUE THREAD

**Issue by BigBlueHat** [RWCBook/transitions-spec#2]
Somebody was working late again...maybe. :sleeping: :arrow_left:  :coffee:  :wink:

It currently says it's the "PROFILE OBJECT DISPLAY Spec"...but it's not...afaict. :smile:

**Comment by mamund** [comment]
right - that's a "copy" bug. i'll update the README​

**Comment by mamund** [comment]
thanks @BigBlueHat!

closed
